package main

import (
	"bytes"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"time"

	"github.com/vortex/go-docx/pkg/docx"
	. "github.com/vortex/go-docx/visual-regtest/internal/regtest"
)

// 25 — Comments
func genComments() (*docx.Document, error) {
	doc, err := docx.New()
	if err != nil {
		return nil, err
	}
	if _, err := doc.AddHeading("Document with Comments", 1); err != nil {
		return nil, err
	}

	para, err := doc.AddParagraph("")
	if err != nil {
		return nil, err
	}
	run1, err := para.AddRun("This text has a comment. ")
	if err != nil {
		return nil, err
	}
	if _, err := doc.AddComment([]*docx.Run{run1}, "This is an important comment.", "Reviewer", StrPtr("R")); err != nil {
		return nil, err
	}

	run2, err := para.AddRun("This text also has a comment.")
	if err != nil {
		return nil, err
	}
	if _, err := doc.AddComment([]*docx.Run{run2}, "Another comment by a different author.", "Editor", StrPtr("E")); err != nil {
		return nil, err
	}

	return doc, nil
}

// 26 — Core properties
func genCoreProperties() (*docx.Document, error) {
	doc, err := docx.New()
	if err != nil {
		return nil, err
	}

	cp, err := doc.CoreProperties()
	if err != nil {
		return nil, err
	}
	if err := cp.SetAuthor("Jane Doe"); err != nil {
		return nil, err
	}
	if err := cp.SetTitle("Test Document — Core Properties"); err != nil {
		return nil, err
	}
	if err := cp.SetSubject("QA Testing"); err != nil {
		return nil, err
	}
	if err := cp.SetKeywords("test, docx, go-docx, core-properties"); err != nil {
		return nil, err
	}
	if err := cp.SetCategory("Testing"); err != nil {
		return nil, err
	}
	if err := cp.SetComments("Generated by gen-files visual regression test."); err != nil {
		return nil, err
	}
	if err := cp.SetLastModifiedBy("Build System"); err != nil {
		return nil, err
	}
	if err := cp.SetLanguage("en-US"); err != nil {
		return nil, err
	}
	if err := cp.SetVersion("1.0.0"); err != nil {
		return nil, err
	}
	if err := cp.SetRevision(42); err != nil {
		return nil, err
	}
	cp.SetCreated(time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC))
	cp.SetModified(time.Date(2025, 6, 15, 12, 0, 0, 0, time.UTC))

	if _, err := doc.AddHeading("Core Properties Test", 1); err != nil {
		return nil, err
	}
	if _, err := doc.AddParagraph("Open File → Properties to verify metadata."); err != nil {
		return nil, err
	}
	return doc, nil
}

// 28 — Mixed content: headings + paragraphs + tables + page breaks
func genMixedContent() (*docx.Document, error) {
	doc, err := docx.New()
	if err != nil {
		return nil, err
	}

	if _, err := doc.AddHeading("Mixed Content Document", 0); err != nil {
		return nil, err
	}
	if _, err := doc.AddParagraph("This document exercises mixed content types."); err != nil {
		return nil, err
	}

	if _, err := doc.AddHeading("Text Section", 1); err != nil {
		return nil, err
	}
	for i := 1; i <= 3; i++ {
		if _, err := doc.AddParagraph(fmt.Sprintf("Paragraph %d: Lorem ipsum dolor sit amet.", i)); err != nil {
			return nil, err
		}
	}

	if _, err := doc.AddHeading("Table Section", 1); err != nil {
		return nil, err
	}
	tbl, err := doc.AddTable(3, 4)
	if err != nil {
		return nil, err
	}
	headers := []string{"Name", "Age", "City", "Score"}
	for i, h := range headers {
		cell, _ := tbl.CellAt(0, i)
		cell.SetText(h)
	}
	data := [][]string{
		{"Alice", "30", "New York", "95"},
		{"Bob", "25", "London", "87"},
	}
	for r, row := range data {
		for c, val := range row {
			cell, _ := tbl.CellAt(r+1, c)
			cell.SetText(val)
		}
	}

	if _, err := doc.AddParagraph(""); err != nil {
		return nil, err
	}
	if _, err := doc.AddPageBreak(); err != nil {
		return nil, err
	}
	if _, err := doc.AddHeading("After Page Break", 1); err != nil {
		return nil, err
	}
	if _, err := doc.AddParagraph("Final content after page break."); err != nil {
		return nil, err
	}

	return doc, nil
}

// 37 — InsertParagraphBefore
func genInsertParagraphBefore() (*docx.Document, error) {
	doc, err := docx.New()
	if err != nil {
		return nil, err
	}
	if _, err := doc.AddHeading("InsertParagraphBefore", 1); err != nil {
		return nil, err
	}

	p1, err := doc.AddParagraph("Paragraph A (added first)")
	if err != nil {
		return nil, err
	}
	if _, err := doc.AddParagraph("Paragraph C (added second)"); err != nil {
		return nil, err
	}

	if _, err := p1.InsertParagraphBefore("Paragraph B (inserted before A)"); err != nil {
		return nil, err
	}

	return doc, nil
}

// 38 — Inline image (generated PNG)
func genInlineImage() (*docx.Document, error) {
	doc, err := docx.New()
	if err != nil {
		return nil, err
	}
	if _, err := doc.AddHeading("Inline Image", 1); err != nil {
		return nil, err
	}
	if _, err := doc.AddParagraph("Below is a programmatically generated image:"); err != nil {
		return nil, err
	}

	img := image.NewRGBA(image.Rect(0, 0, 200, 100))
	for y := 0; y < 100; y++ {
		for x := 0; x < 200; x++ {
			img.Set(x, y, color.RGBA{
				R: uint8(x * 255 / 200),
				G: uint8(y * 255 / 100),
				B: 128,
				A: 255,
			})
		}
	}
	var buf bytes.Buffer
	if err := png.Encode(&buf, img); err != nil {
		return nil, fmt.Errorf("encoding PNG: %w", err)
	}

	reader := bytes.NewReader(buf.Bytes())
	w := int64(docx.Inches(2).Emu())
	h := int64(docx.Inches(1).Emu())
	if _, err := doc.AddPicture(reader, &w, &h); err != nil {
		return nil, fmt.Errorf("add picture: %w", err)
	}

	if _, err := doc.AddParagraph("Image above should be 2\" × 1\" with a gradient."); err != nil {
		return nil, err
	}
	return doc, nil
}

// 39 — Paragraph with multiple styled runs
func genMultipleRuns() (*docx.Document, error) {
	doc, err := docx.New()
	if err != nil {
		return nil, err
	}
	if _, err := doc.AddHeading("Multiple Runs in One Paragraph", 1); err != nil {
		return nil, err
	}

	para, err := doc.AddParagraph("")
	if err != nil {
		return nil, err
	}

	if _, err := para.AddRun("Normal "); err != nil {
		return nil, err
	}

	r1, err := para.AddRun("Red Bold ")
	if err != nil {
		return nil, err
	}
	if err := r1.SetBold(BoolPtr(true)); err != nil {
		return nil, err
	}
	rgb1 := docx.NewRGBColor(0xFF, 0, 0)
	if err := r1.Font().Color().SetRGB(&rgb1); err != nil {
		return nil, err
	}

	r2, err := para.AddRun("Blue Italic ")
	if err != nil {
		return nil, err
	}
	if err := r2.SetItalic(BoolPtr(true)); err != nil {
		return nil, err
	}
	rgb2 := docx.NewRGBColor(0, 0, 0xFF)
	if err := r2.Font().Color().SetRGB(&rgb2); err != nil {
		return nil, err
	}

	r3, err := para.AddRun("Large Green ")
	if err != nil {
		return nil, err
	}
	sz := docx.Pt(24)
	if err := r3.Font().SetSize(&sz); err != nil {
		return nil, err
	}
	rgb3 := docx.NewRGBColor(0, 0x80, 0)
	if err := r3.Font().Color().SetRGB(&rgb3); err != nil {
		return nil, err
	}

	r4, err := para.AddRun("Small Underline")
	if err != nil {
		return nil, err
	}
	sz2 := docx.Pt(8)
	if err := r4.Font().SetSize(&sz2); err != nil {
		return nil, err
	}
	u := docx.UnderlineSingle()
	if err := r4.SetUnderline(&u); err != nil {
		return nil, err
	}

	return doc, nil
}

// 47 — Large document (stress test)
func genLargeDocument() (*docx.Document, error) {
	doc, err := docx.New()
	if err != nil {
		return nil, err
	}
	if _, err := doc.AddHeading("Large Document Stress Test", 0); err != nil {
		return nil, err
	}

	for chapter := 1; chapter <= 5; chapter++ {
		if _, err := doc.AddHeading(fmt.Sprintf("Chapter %d", chapter), 1); err != nil {
			return nil, err
		}
		for section := 1; section <= 3; section++ {
			if _, err := doc.AddHeading(fmt.Sprintf("Section %d.%d", chapter, section), 2); err != nil {
				return nil, err
			}
			for p := 1; p <= 5; p++ {
				if _, err := doc.AddParagraph(fmt.Sprintf(
					"Chapter %d, Section %d, Paragraph %d: Lorem ipsum dolor sit amet, consectetur adipiscing elit. "+
						"Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
					chapter, section, p,
				)); err != nil {
					return nil, err
				}
			}
		}

		tbl, err := doc.AddTable(3, 3)
		if err != nil {
			return nil, err
		}
		for r := 0; r < 3; r++ {
			for c := 0; c < 3; c++ {
				cell, _ := tbl.CellAt(r, c)
				cell.SetText(fmt.Sprintf("Ch%d R%dC%d", chapter, r, c))
			}
		}
		if _, err := doc.AddParagraph(""); err != nil {
			return nil, err
		}
	}

	return doc, nil
}
