// Code generated by codegen; DO NOT EDIT.

package oxml

import (
	"fmt"
)

// Ensure imports are used.
var _ = fmt.Sprintf

// --- CT_Drawing ---

// CT_Drawing — drawing element containing DrawingML objects
type CT_Drawing struct {
	Element
}

// --- CT_LastRenderedPageBreak ---

// CT_LastRenderedPageBreak — last rendered page break element
type CT_LastRenderedPageBreak struct {
	Element
}
