// Code generated by codegen; DO NOT EDIT.

package oxml

import (
	"fmt"
)

// Ensure imports are used.
var _ = fmt.Sprintf

// --- CT_Hyperlink ---

// CT_Hyperlink — hyperlink element
type CT_Hyperlink struct {
	Element
}

// RList returns all <w:r> child elements.
func (e *CT_Hyperlink) RList() []*CT_R {
	children := e.FindAllChildren("w:r")
	result := make([]*CT_R, len(children))
	for i, c := range children {
		result[i] = &CT_R{Element{e: c}}
	}
	return result
}

// AddR adds a new <w:r> in correct sequence.
func (e *CT_Hyperlink) AddR() *CT_R {
	return e.addR()
}

// addR adds a new <w:r> unconditionally in correct sequence.
func (e *CT_Hyperlink) addR() *CT_R {
	child := e.newR()
	e.insertR(child)
	return child
}

// newR creates a detached <w:r> element.
func (e *CT_Hyperlink) newR() *CT_R {
	el := OxmlElement("w:r")
	return &CT_R{Element{e: el}}
}

// insertR inserts child before first successor.
func (e *CT_Hyperlink) insertR(child *CT_R) *CT_R {
	e.InsertElementBefore(child.e)
	return child
}

// RId returns the value of the "r:id" attribute, or "" if absent.
func (e *CT_Hyperlink) RId() string {
	val, ok := e.GetAttr("r:id")
	if !ok {
		return ""
	}
	return val
}

// SetRId sets the "r:id" attribute.
// Passing "" removes it.
func (e *CT_Hyperlink) SetRId(v string) error {
	if v == "" {
		e.RemoveAttr("r:id")
		return nil
	}
	s, err := formatStringAttr(v)
	if err != nil {
		return fmt.Errorf("CT_Hyperlink.SetRId: %w", err)
	}
	e.SetAttr("r:id", s)
	return nil
}

// Anchor returns the value of the "w:anchor" attribute, or "" if absent.
func (e *CT_Hyperlink) Anchor() string {
	val, ok := e.GetAttr("w:anchor")
	if !ok {
		return ""
	}
	return val
}

// SetAnchor sets the "w:anchor" attribute.
// Passing "" removes it.
func (e *CT_Hyperlink) SetAnchor(v string) error {
	if v == "" {
		e.RemoveAttr("w:anchor")
		return nil
	}
	s, err := formatStringAttr(v)
	if err != nil {
		return fmt.Errorf("CT_Hyperlink.SetAnchor: %w", err)
	}
	e.SetAttr("w:anchor", s)
	return nil
}

// History returns the value of the "w:history" attribute, or true if absent.
func (e *CT_Hyperlink) History() bool {
	val, ok := e.GetAttr("w:history")
	if !ok {
		return true
	}
	return parseBoolAttr(val)
}

// SetHistory sets the "w:history" attribute.
// Passing true removes it.
func (e *CT_Hyperlink) SetHistory(v bool) error {
	if v == true {
		e.RemoveAttr("w:history")
		return nil
	}
	s, err := formatBoolAttr(v)
	if err != nil {
		return fmt.Errorf("CT_Hyperlink.SetHistory: %w", err)
	}
	e.SetAttr("w:history", s)
	return nil
}
