// Code generated by codegen; DO NOT EDIT.

package oxml

import (
	"fmt"
)

// Ensure imports are used.
var _ = fmt.Sprintf

// --- CT_CoreProperties ---

// CT_CoreProperties — core properties element (Dublin Core metadata)
type CT_CoreProperties struct {
	Element
}

// Category returns the <cp:category> child element, or nil if not present.
func (e *CT_CoreProperties) Category() *CT_CorePropText {
	child := e.FindChild("cp:category")
	if child == nil {
		return nil
	}
	return &CT_CorePropText{Element{e: child}}
}

// GetOrAddCategory returns <cp:category>, creating it if not present.
func (e *CT_CoreProperties) GetOrAddCategory() *CT_CorePropText {
	child := e.Category()
	if child != nil {
		return child
	}
	return e.addCategory()
}

// RemoveCategory removes all <cp:category> child elements.
func (e *CT_CoreProperties) RemoveCategory() {
	e.RemoveAll("cp:category")
}

// addCategory adds a new <cp:category> in correct sequence.
func (e *CT_CoreProperties) addCategory() *CT_CorePropText {
	child := e.newCategory()
	e.insertCategory(child)
	return child
}

// newCategory creates a detached <cp:category> element.
func (e *CT_CoreProperties) newCategory() *CT_CorePropText {
	el := OxmlElement("cp:category")
	return &CT_CorePropText{Element{e: el}}
}

// insertCategory inserts child before first successor.
func (e *CT_CoreProperties) insertCategory(child *CT_CorePropText) *CT_CorePropText {
	e.InsertElementBefore(child.e)
	return child
}

// ContentStatus returns the <cp:contentStatus> child element, or nil if not present.
func (e *CT_CoreProperties) ContentStatus() *CT_CorePropText {
	child := e.FindChild("cp:contentStatus")
	if child == nil {
		return nil
	}
	return &CT_CorePropText{Element{e: child}}
}

// GetOrAddContentStatus returns <cp:contentStatus>, creating it if not present.
func (e *CT_CoreProperties) GetOrAddContentStatus() *CT_CorePropText {
	child := e.ContentStatus()
	if child != nil {
		return child
	}
	return e.addContentStatus()
}

// RemoveContentStatus removes all <cp:contentStatus> child elements.
func (e *CT_CoreProperties) RemoveContentStatus() {
	e.RemoveAll("cp:contentStatus")
}

// addContentStatus adds a new <cp:contentStatus> in correct sequence.
func (e *CT_CoreProperties) addContentStatus() *CT_CorePropText {
	child := e.newContentStatus()
	e.insertContentStatus(child)
	return child
}

// newContentStatus creates a detached <cp:contentStatus> element.
func (e *CT_CoreProperties) newContentStatus() *CT_CorePropText {
	el := OxmlElement("cp:contentStatus")
	return &CT_CorePropText{Element{e: el}}
}

// insertContentStatus inserts child before first successor.
func (e *CT_CoreProperties) insertContentStatus(child *CT_CorePropText) *CT_CorePropText {
	e.InsertElementBefore(child.e)
	return child
}

// Created returns the <dcterms:created> child element, or nil if not present.
func (e *CT_CoreProperties) Created() *CT_CorePropText {
	child := e.FindChild("dcterms:created")
	if child == nil {
		return nil
	}
	return &CT_CorePropText{Element{e: child}}
}

// GetOrAddCreated returns <dcterms:created>, creating it if not present.
func (e *CT_CoreProperties) GetOrAddCreated() *CT_CorePropText {
	child := e.Created()
	if child != nil {
		return child
	}
	return e.addCreated()
}

// RemoveCreated removes all <dcterms:created> child elements.
func (e *CT_CoreProperties) RemoveCreated() {
	e.RemoveAll("dcterms:created")
}

// addCreated adds a new <dcterms:created> in correct sequence.
func (e *CT_CoreProperties) addCreated() *CT_CorePropText {
	child := e.newCreated()
	e.insertCreated(child)
	return child
}

// newCreated creates a detached <dcterms:created> element.
func (e *CT_CoreProperties) newCreated() *CT_CorePropText {
	el := OxmlElement("dcterms:created")
	return &CT_CorePropText{Element{e: el}}
}

// insertCreated inserts child before first successor.
func (e *CT_CoreProperties) insertCreated(child *CT_CorePropText) *CT_CorePropText {
	e.InsertElementBefore(child.e)
	return child
}

// Creator returns the <dc:creator> child element, or nil if not present.
func (e *CT_CoreProperties) Creator() *CT_CorePropText {
	child := e.FindChild("dc:creator")
	if child == nil {
		return nil
	}
	return &CT_CorePropText{Element{e: child}}
}

// GetOrAddCreator returns <dc:creator>, creating it if not present.
func (e *CT_CoreProperties) GetOrAddCreator() *CT_CorePropText {
	child := e.Creator()
	if child != nil {
		return child
	}
	return e.addCreator()
}

// RemoveCreator removes all <dc:creator> child elements.
func (e *CT_CoreProperties) RemoveCreator() {
	e.RemoveAll("dc:creator")
}

// addCreator adds a new <dc:creator> in correct sequence.
func (e *CT_CoreProperties) addCreator() *CT_CorePropText {
	child := e.newCreator()
	e.insertCreator(child)
	return child
}

// newCreator creates a detached <dc:creator> element.
func (e *CT_CoreProperties) newCreator() *CT_CorePropText {
	el := OxmlElement("dc:creator")
	return &CT_CorePropText{Element{e: el}}
}

// insertCreator inserts child before first successor.
func (e *CT_CoreProperties) insertCreator(child *CT_CorePropText) *CT_CorePropText {
	e.InsertElementBefore(child.e)
	return child
}

// Description returns the <dc:description> child element, or nil if not present.
func (e *CT_CoreProperties) Description() *CT_CorePropText {
	child := e.FindChild("dc:description")
	if child == nil {
		return nil
	}
	return &CT_CorePropText{Element{e: child}}
}

// GetOrAddDescription returns <dc:description>, creating it if not present.
func (e *CT_CoreProperties) GetOrAddDescription() *CT_CorePropText {
	child := e.Description()
	if child != nil {
		return child
	}
	return e.addDescription()
}

// RemoveDescription removes all <dc:description> child elements.
func (e *CT_CoreProperties) RemoveDescription() {
	e.RemoveAll("dc:description")
}

// addDescription adds a new <dc:description> in correct sequence.
func (e *CT_CoreProperties) addDescription() *CT_CorePropText {
	child := e.newDescription()
	e.insertDescription(child)
	return child
}

// newDescription creates a detached <dc:description> element.
func (e *CT_CoreProperties) newDescription() *CT_CorePropText {
	el := OxmlElement("dc:description")
	return &CT_CorePropText{Element{e: el}}
}

// insertDescription inserts child before first successor.
func (e *CT_CoreProperties) insertDescription(child *CT_CorePropText) *CT_CorePropText {
	e.InsertElementBefore(child.e)
	return child
}

// Identifier returns the <dc:identifier> child element, or nil if not present.
func (e *CT_CoreProperties) Identifier() *CT_CorePropText {
	child := e.FindChild("dc:identifier")
	if child == nil {
		return nil
	}
	return &CT_CorePropText{Element{e: child}}
}

// GetOrAddIdentifier returns <dc:identifier>, creating it if not present.
func (e *CT_CoreProperties) GetOrAddIdentifier() *CT_CorePropText {
	child := e.Identifier()
	if child != nil {
		return child
	}
	return e.addIdentifier()
}

// RemoveIdentifier removes all <dc:identifier> child elements.
func (e *CT_CoreProperties) RemoveIdentifier() {
	e.RemoveAll("dc:identifier")
}

// addIdentifier adds a new <dc:identifier> in correct sequence.
func (e *CT_CoreProperties) addIdentifier() *CT_CorePropText {
	child := e.newIdentifier()
	e.insertIdentifier(child)
	return child
}

// newIdentifier creates a detached <dc:identifier> element.
func (e *CT_CoreProperties) newIdentifier() *CT_CorePropText {
	el := OxmlElement("dc:identifier")
	return &CT_CorePropText{Element{e: el}}
}

// insertIdentifier inserts child before first successor.
func (e *CT_CoreProperties) insertIdentifier(child *CT_CorePropText) *CT_CorePropText {
	e.InsertElementBefore(child.e)
	return child
}

// Keywords returns the <cp:keywords> child element, or nil if not present.
func (e *CT_CoreProperties) Keywords() *CT_CorePropText {
	child := e.FindChild("cp:keywords")
	if child == nil {
		return nil
	}
	return &CT_CorePropText{Element{e: child}}
}

// GetOrAddKeywords returns <cp:keywords>, creating it if not present.
func (e *CT_CoreProperties) GetOrAddKeywords() *CT_CorePropText {
	child := e.Keywords()
	if child != nil {
		return child
	}
	return e.addKeywords()
}

// RemoveKeywords removes all <cp:keywords> child elements.
func (e *CT_CoreProperties) RemoveKeywords() {
	e.RemoveAll("cp:keywords")
}

// addKeywords adds a new <cp:keywords> in correct sequence.
func (e *CT_CoreProperties) addKeywords() *CT_CorePropText {
	child := e.newKeywords()
	e.insertKeywords(child)
	return child
}

// newKeywords creates a detached <cp:keywords> element.
func (e *CT_CoreProperties) newKeywords() *CT_CorePropText {
	el := OxmlElement("cp:keywords")
	return &CT_CorePropText{Element{e: el}}
}

// insertKeywords inserts child before first successor.
func (e *CT_CoreProperties) insertKeywords(child *CT_CorePropText) *CT_CorePropText {
	e.InsertElementBefore(child.e)
	return child
}

// Language returns the <dc:language> child element, or nil if not present.
func (e *CT_CoreProperties) Language() *CT_CorePropText {
	child := e.FindChild("dc:language")
	if child == nil {
		return nil
	}
	return &CT_CorePropText{Element{e: child}}
}

// GetOrAddLanguage returns <dc:language>, creating it if not present.
func (e *CT_CoreProperties) GetOrAddLanguage() *CT_CorePropText {
	child := e.Language()
	if child != nil {
		return child
	}
	return e.addLanguage()
}

// RemoveLanguage removes all <dc:language> child elements.
func (e *CT_CoreProperties) RemoveLanguage() {
	e.RemoveAll("dc:language")
}

// addLanguage adds a new <dc:language> in correct sequence.
func (e *CT_CoreProperties) addLanguage() *CT_CorePropText {
	child := e.newLanguage()
	e.insertLanguage(child)
	return child
}

// newLanguage creates a detached <dc:language> element.
func (e *CT_CoreProperties) newLanguage() *CT_CorePropText {
	el := OxmlElement("dc:language")
	return &CT_CorePropText{Element{e: el}}
}

// insertLanguage inserts child before first successor.
func (e *CT_CoreProperties) insertLanguage(child *CT_CorePropText) *CT_CorePropText {
	e.InsertElementBefore(child.e)
	return child
}

// LastModifiedBy returns the <cp:lastModifiedBy> child element, or nil if not present.
func (e *CT_CoreProperties) LastModifiedBy() *CT_CorePropText {
	child := e.FindChild("cp:lastModifiedBy")
	if child == nil {
		return nil
	}
	return &CT_CorePropText{Element{e: child}}
}

// GetOrAddLastModifiedBy returns <cp:lastModifiedBy>, creating it if not present.
func (e *CT_CoreProperties) GetOrAddLastModifiedBy() *CT_CorePropText {
	child := e.LastModifiedBy()
	if child != nil {
		return child
	}
	return e.addLastModifiedBy()
}

// RemoveLastModifiedBy removes all <cp:lastModifiedBy> child elements.
func (e *CT_CoreProperties) RemoveLastModifiedBy() {
	e.RemoveAll("cp:lastModifiedBy")
}

// addLastModifiedBy adds a new <cp:lastModifiedBy> in correct sequence.
func (e *CT_CoreProperties) addLastModifiedBy() *CT_CorePropText {
	child := e.newLastModifiedBy()
	e.insertLastModifiedBy(child)
	return child
}

// newLastModifiedBy creates a detached <cp:lastModifiedBy> element.
func (e *CT_CoreProperties) newLastModifiedBy() *CT_CorePropText {
	el := OxmlElement("cp:lastModifiedBy")
	return &CT_CorePropText{Element{e: el}}
}

// insertLastModifiedBy inserts child before first successor.
func (e *CT_CoreProperties) insertLastModifiedBy(child *CT_CorePropText) *CT_CorePropText {
	e.InsertElementBefore(child.e)
	return child
}

// LastPrinted returns the <cp:lastPrinted> child element, or nil if not present.
func (e *CT_CoreProperties) LastPrinted() *CT_CorePropText {
	child := e.FindChild("cp:lastPrinted")
	if child == nil {
		return nil
	}
	return &CT_CorePropText{Element{e: child}}
}

// GetOrAddLastPrinted returns <cp:lastPrinted>, creating it if not present.
func (e *CT_CoreProperties) GetOrAddLastPrinted() *CT_CorePropText {
	child := e.LastPrinted()
	if child != nil {
		return child
	}
	return e.addLastPrinted()
}

// RemoveLastPrinted removes all <cp:lastPrinted> child elements.
func (e *CT_CoreProperties) RemoveLastPrinted() {
	e.RemoveAll("cp:lastPrinted")
}

// addLastPrinted adds a new <cp:lastPrinted> in correct sequence.
func (e *CT_CoreProperties) addLastPrinted() *CT_CorePropText {
	child := e.newLastPrinted()
	e.insertLastPrinted(child)
	return child
}

// newLastPrinted creates a detached <cp:lastPrinted> element.
func (e *CT_CoreProperties) newLastPrinted() *CT_CorePropText {
	el := OxmlElement("cp:lastPrinted")
	return &CT_CorePropText{Element{e: el}}
}

// insertLastPrinted inserts child before first successor.
func (e *CT_CoreProperties) insertLastPrinted(child *CT_CorePropText) *CT_CorePropText {
	e.InsertElementBefore(child.e)
	return child
}

// Modified returns the <dcterms:modified> child element, or nil if not present.
func (e *CT_CoreProperties) Modified() *CT_CorePropText {
	child := e.FindChild("dcterms:modified")
	if child == nil {
		return nil
	}
	return &CT_CorePropText{Element{e: child}}
}

// GetOrAddModified returns <dcterms:modified>, creating it if not present.
func (e *CT_CoreProperties) GetOrAddModified() *CT_CorePropText {
	child := e.Modified()
	if child != nil {
		return child
	}
	return e.addModified()
}

// RemoveModified removes all <dcterms:modified> child elements.
func (e *CT_CoreProperties) RemoveModified() {
	e.RemoveAll("dcterms:modified")
}

// addModified adds a new <dcterms:modified> in correct sequence.
func (e *CT_CoreProperties) addModified() *CT_CorePropText {
	child := e.newModified()
	e.insertModified(child)
	return child
}

// newModified creates a detached <dcterms:modified> element.
func (e *CT_CoreProperties) newModified() *CT_CorePropText {
	el := OxmlElement("dcterms:modified")
	return &CT_CorePropText{Element{e: el}}
}

// insertModified inserts child before first successor.
func (e *CT_CoreProperties) insertModified(child *CT_CorePropText) *CT_CorePropText {
	e.InsertElementBefore(child.e)
	return child
}

// Revision returns the <cp:revision> child element, or nil if not present.
func (e *CT_CoreProperties) Revision() *CT_CorePropText {
	child := e.FindChild("cp:revision")
	if child == nil {
		return nil
	}
	return &CT_CorePropText{Element{e: child}}
}

// GetOrAddRevision returns <cp:revision>, creating it if not present.
func (e *CT_CoreProperties) GetOrAddRevision() *CT_CorePropText {
	child := e.Revision()
	if child != nil {
		return child
	}
	return e.addRevision()
}

// RemoveRevision removes all <cp:revision> child elements.
func (e *CT_CoreProperties) RemoveRevision() {
	e.RemoveAll("cp:revision")
}

// addRevision adds a new <cp:revision> in correct sequence.
func (e *CT_CoreProperties) addRevision() *CT_CorePropText {
	child := e.newRevision()
	e.insertRevision(child)
	return child
}

// newRevision creates a detached <cp:revision> element.
func (e *CT_CoreProperties) newRevision() *CT_CorePropText {
	el := OxmlElement("cp:revision")
	return &CT_CorePropText{Element{e: el}}
}

// insertRevision inserts child before first successor.
func (e *CT_CoreProperties) insertRevision(child *CT_CorePropText) *CT_CorePropText {
	e.InsertElementBefore(child.e)
	return child
}

// Subject returns the <dc:subject> child element, or nil if not present.
func (e *CT_CoreProperties) Subject() *CT_CorePropText {
	child := e.FindChild("dc:subject")
	if child == nil {
		return nil
	}
	return &CT_CorePropText{Element{e: child}}
}

// GetOrAddSubject returns <dc:subject>, creating it if not present.
func (e *CT_CoreProperties) GetOrAddSubject() *CT_CorePropText {
	child := e.Subject()
	if child != nil {
		return child
	}
	return e.addSubject()
}

// RemoveSubject removes all <dc:subject> child elements.
func (e *CT_CoreProperties) RemoveSubject() {
	e.RemoveAll("dc:subject")
}

// addSubject adds a new <dc:subject> in correct sequence.
func (e *CT_CoreProperties) addSubject() *CT_CorePropText {
	child := e.newSubject()
	e.insertSubject(child)
	return child
}

// newSubject creates a detached <dc:subject> element.
func (e *CT_CoreProperties) newSubject() *CT_CorePropText {
	el := OxmlElement("dc:subject")
	return &CT_CorePropText{Element{e: el}}
}

// insertSubject inserts child before first successor.
func (e *CT_CoreProperties) insertSubject(child *CT_CorePropText) *CT_CorePropText {
	e.InsertElementBefore(child.e)
	return child
}

// Title returns the <dc:title> child element, or nil if not present.
func (e *CT_CoreProperties) Title() *CT_CorePropText {
	child := e.FindChild("dc:title")
	if child == nil {
		return nil
	}
	return &CT_CorePropText{Element{e: child}}
}

// GetOrAddTitle returns <dc:title>, creating it if not present.
func (e *CT_CoreProperties) GetOrAddTitle() *CT_CorePropText {
	child := e.Title()
	if child != nil {
		return child
	}
	return e.addTitle()
}

// RemoveTitle removes all <dc:title> child elements.
func (e *CT_CoreProperties) RemoveTitle() {
	e.RemoveAll("dc:title")
}

// addTitle adds a new <dc:title> in correct sequence.
func (e *CT_CoreProperties) addTitle() *CT_CorePropText {
	child := e.newTitle()
	e.insertTitle(child)
	return child
}

// newTitle creates a detached <dc:title> element.
func (e *CT_CoreProperties) newTitle() *CT_CorePropText {
	el := OxmlElement("dc:title")
	return &CT_CorePropText{Element{e: el}}
}

// insertTitle inserts child before first successor.
func (e *CT_CoreProperties) insertTitle(child *CT_CorePropText) *CT_CorePropText {
	e.InsertElementBefore(child.e)
	return child
}

// Version returns the <cp:version> child element, or nil if not present.
func (e *CT_CoreProperties) Version() *CT_CorePropText {
	child := e.FindChild("cp:version")
	if child == nil {
		return nil
	}
	return &CT_CorePropText{Element{e: child}}
}

// GetOrAddVersion returns <cp:version>, creating it if not present.
func (e *CT_CoreProperties) GetOrAddVersion() *CT_CorePropText {
	child := e.Version()
	if child != nil {
		return child
	}
	return e.addVersion()
}

// RemoveVersion removes all <cp:version> child elements.
func (e *CT_CoreProperties) RemoveVersion() {
	e.RemoveAll("cp:version")
}

// addVersion adds a new <cp:version> in correct sequence.
func (e *CT_CoreProperties) addVersion() *CT_CorePropText {
	child := e.newVersion()
	e.insertVersion(child)
	return child
}

// newVersion creates a detached <cp:version> element.
func (e *CT_CoreProperties) newVersion() *CT_CorePropText {
	el := OxmlElement("cp:version")
	return &CT_CorePropText{Element{e: el}}
}

// insertVersion inserts child before first successor.
func (e *CT_CoreProperties) insertVersion(child *CT_CorePropText) *CT_CorePropText {
	e.InsertElementBefore(child.e)
	return child
}

// --- CT_CorePropText ---

// CT_CorePropText — simple text holder element for core properties
type CT_CorePropText struct {
	Element
}
