// Code generated by codegen; DO NOT EDIT.

package oxml

import (
	"fmt"
)

// Ensure imports are used.
var _ = fmt.Sprintf

// --- CT_Settings ---

// CT_Settings — settings root element
type CT_Settings struct {
	Element
}

// EvenAndOddHeaders returns the <w:evenAndOddHeaders> child element, or nil if not present.
func (e *CT_Settings) EvenAndOddHeaders() *CT_OnOff {
	child := e.FindChild("w:evenAndOddHeaders")
	if child == nil {
		return nil
	}
	return &CT_OnOff{Element{e: child}}
}

// GetOrAddEvenAndOddHeaders returns <w:evenAndOddHeaders>, creating it if not present.
func (e *CT_Settings) GetOrAddEvenAndOddHeaders() *CT_OnOff {
	child := e.EvenAndOddHeaders()
	if child != nil {
		return child
	}
	return e.addEvenAndOddHeaders()
}

// RemoveEvenAndOddHeaders removes all <w:evenAndOddHeaders> child elements.
func (e *CT_Settings) RemoveEvenAndOddHeaders() {
	e.RemoveAll("w:evenAndOddHeaders")
}

// addEvenAndOddHeaders adds a new <w:evenAndOddHeaders> in correct sequence.
func (e *CT_Settings) addEvenAndOddHeaders() *CT_OnOff {
	child := e.newEvenAndOddHeaders()
	e.insertEvenAndOddHeaders(child)
	return child
}

// newEvenAndOddHeaders creates a detached <w:evenAndOddHeaders> element.
func (e *CT_Settings) newEvenAndOddHeaders() *CT_OnOff {
	el := OxmlElement("w:evenAndOddHeaders")
	return &CT_OnOff{Element{e: el}}
}

// insertEvenAndOddHeaders inserts child before first successor.
func (e *CT_Settings) insertEvenAndOddHeaders(child *CT_OnOff) *CT_OnOff {
	e.InsertElementBefore(child.e, "w:bookFoldRevPrinting", "w:bookFoldPrinting", "w:bookFoldPrintingSheets", "w:drawingGridHorizontalSpacing", "w:drawingGridVerticalSpacing", "w:displayHorizontalDrawingGridEvery", "w:displayVerticalDrawingGridEvery", "w:doNotUseMarginsForDrawingGridOrigin", "w:drawingGridHorizontalOrigin", "w:drawingGridVerticalOrigin", "w:doNotShadeFormData", "w:noPunctuationKerning", "w:characterSpacingControl", "w:printTwoOnOne", "w:strictFirstAndLastChars", "w:noLineBreaksAfter", "w:noLineBreaksBefore", "w:savePreviewPicture", "w:doNotValidateAgainstSchema", "w:saveInvalidXml", "w:ignoreMixedContent", "w:alwaysShowPlaceholderText", "w:doNotDemarcateInvalidXml", "w:saveXmlDataOnly", "w:useXSLTWhenSaving", "w:saveThroughXslt", "w:showXMLTags", "w:alwaysMergeEmptyNamespace", "w:updateFields", "w:hdrShapeDefaults", "w:footnotePr", "w:endnotePr", "w:compat", "w:docVars", "w:rsids")
	return child
}
