// Code generated by codegen; DO NOT EDIT.

package oxml

import (
	"fmt"
)

// Ensure imports are used.
var _ = fmt.Sprintf

// --- CT_Numbering ---

// CT_Numbering — numbering root element
type CT_Numbering struct {
	Element
}

// NumList returns all <w:num> child elements.
func (e *CT_Numbering) NumList() []*CT_Num {
	children := e.FindAllChildren("w:num")
	result := make([]*CT_Num, len(children))
	for i, c := range children {
		result[i] = &CT_Num{Element{e: c}}
	}
	return result
}

// AddNum adds a new <w:num> in correct sequence.
func (e *CT_Numbering) AddNum() *CT_Num {
	return e.addNum()
}

// addNum adds a new <w:num> unconditionally in correct sequence.
func (e *CT_Numbering) addNum() *CT_Num {
	child := e.newNum()
	e.insertNum(child)
	return child
}

// newNum creates a detached <w:num> element.
func (e *CT_Numbering) newNum() *CT_Num {
	el := OxmlElement("w:num")
	return &CT_Num{Element{e: el}}
}

// insertNum inserts child before first successor.
func (e *CT_Numbering) insertNum(child *CT_Num) *CT_Num {
	e.InsertElementBefore(child.e, "w:numIdMacAtCleanup")
	return child
}

// --- CT_Num ---

// CT_Num — numbering instance element
type CT_Num struct {
	Element
}

// LvlOverrideList returns all <w:lvlOverride> child elements.
func (e *CT_Num) LvlOverrideList() []*CT_NumLvl {
	children := e.FindAllChildren("w:lvlOverride")
	result := make([]*CT_NumLvl, len(children))
	for i, c := range children {
		result[i] = &CT_NumLvl{Element{e: c}}
	}
	return result
}

// AddLvlOverride adds a new <w:lvlOverride> in correct sequence.
func (e *CT_Num) AddLvlOverride() *CT_NumLvl {
	return e.addLvlOverride()
}

// addLvlOverride adds a new <w:lvlOverride> unconditionally in correct sequence.
func (e *CT_Num) addLvlOverride() *CT_NumLvl {
	child := e.newLvlOverride()
	e.insertLvlOverride(child)
	return child
}

// newLvlOverride creates a detached <w:lvlOverride> element.
func (e *CT_Num) newLvlOverride() *CT_NumLvl {
	el := OxmlElement("w:lvlOverride")
	return &CT_NumLvl{Element{e: el}}
}

// insertLvlOverride inserts child before first successor.
func (e *CT_Num) insertLvlOverride(child *CT_NumLvl) *CT_NumLvl {
	e.InsertElementBefore(child.e)
	return child
}

// AbstractNumId returns the required <w:abstractNumId> child element.
// Returns an error if not present (invalid XML).
func (e *CT_Num) AbstractNumId() (*CT_DecimalNumber, error) {
	child := e.FindChild("w:abstractNumId")
	if child == nil {
		return nil, fmt.Errorf("required <%s> child not present in <%s>", "w:abstractNumId", e.Tag())
	}
	return &CT_DecimalNumber{Element{e: child}}, nil
}

// NumId returns the value of the required "w:numId" attribute.
func (e *CT_Num) NumId() (int, error) {
	val, ok := e.GetAttr("w:numId")
	if !ok {
		return 0, fmt.Errorf("required attribute %q not present on <%s>", "w:numId", e.Tag())
	}
	parsed, err := parseIntAttr(val)
	if err != nil {
		return 0, &ParseAttrError{Element: e.Tag(), Attr: "w:numId", RawValue: val, Err: err}
	}
	return parsed, nil
}

// SetNumId sets the required "w:numId" attribute.
func (e *CT_Num) SetNumId(v int) error {
	s, err := formatIntAttr(v)
	if err != nil {
		return fmt.Errorf("CT_Num.SetNumId: %w", err)
	}
	e.SetAttr("w:numId", s)
	return nil
}

// --- CT_NumLvl ---

// CT_NumLvl — numbering level override element
type CT_NumLvl struct {
	Element
}

// StartOverride returns the <w:startOverride> child element, or nil if not present.
func (e *CT_NumLvl) StartOverride() *CT_DecimalNumber {
	child := e.FindChild("w:startOverride")
	if child == nil {
		return nil
	}
	return &CT_DecimalNumber{Element{e: child}}
}

// GetOrAddStartOverride returns <w:startOverride>, creating it if not present.
func (e *CT_NumLvl) GetOrAddStartOverride() *CT_DecimalNumber {
	child := e.StartOverride()
	if child != nil {
		return child
	}
	return e.addStartOverride()
}

// RemoveStartOverride removes all <w:startOverride> child elements.
func (e *CT_NumLvl) RemoveStartOverride() {
	e.RemoveAll("w:startOverride")
}

// addStartOverride adds a new <w:startOverride> in correct sequence.
func (e *CT_NumLvl) addStartOverride() *CT_DecimalNumber {
	child := e.newStartOverride()
	e.insertStartOverride(child)
	return child
}

// newStartOverride creates a detached <w:startOverride> element.
func (e *CT_NumLvl) newStartOverride() *CT_DecimalNumber {
	el := OxmlElement("w:startOverride")
	return &CT_DecimalNumber{Element{e: el}}
}

// insertStartOverride inserts child before first successor.
func (e *CT_NumLvl) insertStartOverride(child *CT_DecimalNumber) *CT_DecimalNumber {
	e.InsertElementBefore(child.e, "w:lvl")
	return child
}

// Ilvl returns the value of the required "w:ilvl" attribute.
func (e *CT_NumLvl) Ilvl() (int, error) {
	val, ok := e.GetAttr("w:ilvl")
	if !ok {
		return 0, fmt.Errorf("required attribute %q not present on <%s>", "w:ilvl", e.Tag())
	}
	parsed, err := parseIntAttr(val)
	if err != nil {
		return 0, &ParseAttrError{Element: e.Tag(), Attr: "w:ilvl", RawValue: val, Err: err}
	}
	return parsed, nil
}

// SetIlvl sets the required "w:ilvl" attribute.
func (e *CT_NumLvl) SetIlvl(v int) error {
	s, err := formatIntAttr(v)
	if err != nil {
		return fmt.Errorf("CT_NumLvl.SetIlvl: %w", err)
	}
	e.SetAttr("w:ilvl", s)
	return nil
}
