package parts

import (
	"fmt"

	"github.com/vortex/go-docx/pkg/docx/opc"
	"github.com/vortex/go-docx/pkg/docx/oxml"
	"github.com/vortex/go-docx/pkg/docx/templates"
)

// --------------------------------------------------------------------------
// FootnotesPart
// --------------------------------------------------------------------------

// FootnotesPart is the container part for footnotes in the document
// (footnotes.xml).
//
// Inherits StoryPart because footnote bodies can contain images and
// hyperlinks, requiring access to Rels() for rId import on both the
// source and target sides.
type FootnotesPart struct {
	StoryPart
}

// NewFootnotesPart wraps an XmlPart as a FootnotesPart.
func NewFootnotesPart(xp *opc.XmlPart) *FootnotesPart {
	return &FootnotesPart{
		StoryPart: StoryPart{XmlPart: xp},
	}
}

// LoadFootnotesPart is a PartConstructor for loading FootnotesPart from a
// package.
func LoadFootnotesPart(partName opc.PackURI, contentType, _ string, blob []byte, pkg *opc.OpcPackage) (opc.Part, error) {
	xp, err := opc.NewXmlPart(partName, contentType, blob, pkg)
	if err != nil {
		return nil, fmt.Errorf("parts: loading footnotes part %q: %w", partName, err)
	}
	return NewFootnotesPart(xp), nil
}

// DefaultFootnotesPart creates a new FootnotesPart from the default template.
//
// The template contains separator and continuationSeparator footnotes
// (id=-1 and id=0) as generated by Word. Used by GetOrAddFootnotesPart
// when the target document has no footnotes part.
func DefaultFootnotesPart(pkg *opc.OpcPackage) (*FootnotesPart, error) {
	xmlBytes, err := templates.FS.ReadFile("default-footnotes.xml")
	if err != nil {
		return nil, fmt.Errorf("parts: reading default-footnotes.xml: %w", err)
	}
	el, err := oxml.ParseXml(xmlBytes)
	if err != nil {
		return nil, fmt.Errorf("parts: parsing default-footnotes.xml: %w", err)
	}
	pn := opc.PackURI("/word/footnotes.xml")
	xp := opc.NewXmlPartFromElement(pn, opc.CTWmlFootnotes, el, pkg)
	return NewFootnotesPart(xp), nil
}

// --------------------------------------------------------------------------
// EndnotesPart
// --------------------------------------------------------------------------

// EndnotesPart is the container part for endnotes in the document
// (endnotes.xml).
//
// Inherits StoryPart for the same reasons as FootnotesPart.
type EndnotesPart struct {
	StoryPart
}

// NewEndnotesPart wraps an XmlPart as an EndnotesPart.
func NewEndnotesPart(xp *opc.XmlPart) *EndnotesPart {
	return &EndnotesPart{
		StoryPart: StoryPart{XmlPart: xp},
	}
}

// LoadEndnotesPart is a PartConstructor for loading EndnotesPart from a
// package.
func LoadEndnotesPart(partName opc.PackURI, contentType, _ string, blob []byte, pkg *opc.OpcPackage) (opc.Part, error) {
	xp, err := opc.NewXmlPart(partName, contentType, blob, pkg)
	if err != nil {
		return nil, fmt.Errorf("parts: loading endnotes part %q: %w", partName, err)
	}
	return NewEndnotesPart(xp), nil
}

// DefaultEndnotesPart creates a new EndnotesPart from the default template.
//
// The template contains separator and continuationSeparator endnotes
// (id=-1 and id=0) as generated by Word. Used by GetOrAddEndnotesPart
// when the target document has no endnotes part.
func DefaultEndnotesPart(pkg *opc.OpcPackage) (*EndnotesPart, error) {
	xmlBytes, err := templates.FS.ReadFile("default-endnotes.xml")
	if err != nil {
		return nil, fmt.Errorf("parts: reading default-endnotes.xml: %w", err)
	}
	el, err := oxml.ParseXml(xmlBytes)
	if err != nil {
		return nil, fmt.Errorf("parts: parsing default-endnotes.xml: %w", err)
	}
	pn := opc.PackURI("/word/endnotes.xml")
	xp := opc.NewXmlPartFromElement(pn, opc.CTWmlEndnotes, el, pkg)
	return NewEndnotesPart(xp), nil
}
